HELM_RELEASE_NAME ?= milvus
HELM_APPLICATION_NAME ?= milvus
HELM_NAMESPACE ?= milvus
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?= 5.0.13
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?= docker.io
HELM_OCI_NAMESPACE ?=
HELM_REPO_NAME ?= milvus
HELM_REPO_URL ?= https://zilliztech.github.io/milvus-helm
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/$(HELM_APPLICATION_NAME)

include ../_template/base.mk
