HELM_RELEASE_NAME ?= rainbond
HELM_APPLICATION_NAME ?= rainbond
HELM_NAMESPACE ?= rbd-system
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= goodrain
HELM_REPO_URL ?= https://openchart.goodrain.com/goodrain/rainbond
HELM_CHART_REPO ?= goodrain/rainbond

include ../_template/base.mk
