replicaCount: 3

replicaSet:
  enabled: true
  name: rs0
  key: "qJlSywRHAWOysZaow3uE5f3BQAY/1ml/" # change me!

auth:
  enabled: true
  rootUsername: admin
  rootPassword: "password" # Change me!

persistence:
  enabled: true
  storageClass: local-path

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.1"
    memory: "512Mi"
