HELM_RELEASE_NAME ?= sealos
HELM_APPLICATION_NAME ?= sealos
HELM_NAMESPACE ?= sealos
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= seal-io
HELM_REPO_URL ?= https://seal-io.github.io/helm-charts
HELM_CHART_REPO ?= seal-io/sealos

include ../_template/base.mk
