HELM_RELEASE_NAME ?= clickhouse
HELM_APPLICATION_NAME ?= clickhouse
HELM_NAMESPACE ?= clickhouse
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?= 0.3.8
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?= docker.io
HELM_OCI_NAMESPACE ?=
HELM_REPO_NAME ?= altinity
HELM_REPO_URL ?= https://helm.altinity.com
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/$(HELM_APPLICATION_NAME)

include ../_template/base.mk
