HELM_RELEASE_NAME ?= open-webui
HELM_APPLICATION_NAME ?= open-webui
HELM_NAMESPACE ?= open-webui
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= open-webui
HELM_REPO_URL ?= https://helm.openwebui.com
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/open-webui
HELM_LANE ?=

include ../_template/base.mk
