HELM_RELEASE_NAME ?= mlflow
HELM_APPLICATION_NAME ?= mlflow
HELM_NAMESPACE ?= mlflow
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= community-charts
HELM_REPO_URL ?= https://community-charts.github.io
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/mlflow
HELM_LANE ?=

include ../_template/base.mk
