HELM_RELEASE_NAME ?= signoz-otel-gateway
HELM_APPLICATION_NAME ?= signoz-otel-gateway
HELM_NAMESPACE ?= platform
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?= 0.0.4
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= signoz
HELM_REPO_URL ?= https://charts.signoz.io
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/signoz-otel-gateway

include ../_template/base.mk
