HELM_RELEASE_NAME ?= gitlab-runner
HELM_APPLICATION_NAME ?= gitlab-runner
HELM_NAMESPACE ?= gitlab-runner
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= gitlab
HELM_REPO_URL ?= https://charts.gitlab.io
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/gitlab-runner
HELM_LANE ?=

include ../_template/base.mk
