# GitLab Helm Chart Values
# https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml

# Default values for gitlab
# This is a YAML-formatted file

global:
  edition: ce
  hosts:
    domain: gitlab.local
    hostSuffix: ''
    https: false
  ingress:
    enabled: false
  initialRootPassword:
    key: password
    secret: gitlab-gitlab-initial-root-password

gitlab:
  webservice:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
