HELM_RELEASE_NAME ?= openlit
HELM_APPLICATION_NAME ?= openlit
HELM_NAMESPACE ?= openlit
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= openlit
HELM_REPO_URL ?= https://openlit.github.io/helm/
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/openlit

include ../_template/base.mk