HELM_RELEASE_NAME ?= mongodb-community-operator
HELM_APPLICATION_NAME ?= community-operator
HELM_NAMESPACE ?= mongodb-operator
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= mongodb
HELM_REPO_URL ?= https://mongodb.github.io/helm-charts
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/community-operator

include ../_template/base.mk