# K8ssandra Helm Chart Values
# https://github.com/k8ssandra/k8ssandra-helm

cassandra:
  clusterName: cassandra-cluster
  datacenters:
    - name: dc1
      size: 3
      racks:
        - name: rack1
        - name: rack2
        - name: rack3
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi

stargate:
  enabled: false

reaper:
  enabled: false

medusa:
  enabled: false

monitoring:
  prometheus:
    enabled: false
