HELM_RELEASE_NAME ?= flink-operator
HELM_APPLICATION_NAME ?= flink-operator
HELM_NAMESPACE ?= flink-operator
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= flink-operator
HELM_REPO_URL ?= https://downloads.apache.org/flink/flink-kubernetes-operator-1.10.0/
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/flink-kubernetes-operator

include ../_template/base.mk
