HELM_RELEASE_NAME ?= litellm
HELM_APPLICATION_NAME ?= litellm
HELM_NAMESPACE ?= litellm
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= litellm
HELM_REPO_URL ?= https://berriai.github.io/litellm-helm
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/litellm-helm

include ../_template/base.mk
