HELM_RELEASE_NAME ?= kibana
HELM_APPLICATION_NAME ?= kibana
HELM_NAMESPACE ?= elastic
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?= 8.5.1
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?= docker.io
HELM_OCI_NAMESPACE ?=
HELM_REPO_NAME ?= elastic
HELM_REPO_URL ?= https://helm.elastic.co
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/$(HELM_APPLICATION_NAME)

include ../_template/base.mk
