# Nginx Configuration
# https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx

replicaCount: 1

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
