HELM_RELEASE_NAME ?= nacos
HELM_APPLICATION_NAME ?= nacos
HELM_NAMESPACE ?= nacos
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= nacos
HELM_REPO_URL ?= https://nacos-charts.storage.googleapis.com
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/nacos

include ../_template/base.mk
