HELM_RELEASE_NAME ?= grafana
HELM_APPLICATION_NAME ?= grafana
HELM_NAMESPACE ?= grafana
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= grafana
HELM_REPO_URL ?= https://grafana.github.io/helm-charts
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/grafana

include ../_template/base.mk
