HELM_RELEASE_NAME ?= cnpg
HELM_APPLICATION_NAME ?= cloudnative-pg
HELM_NAMESPACE ?= cnpg-system
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= cnpg
HELM_REPO_URL ?= https://cloudnative-pg.github.io/charts
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/cloudnative-pg

include ../_template/base.mk