# Keycloak Configuration
# https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak

replicaCount: 1

keycloak:
  adminUser: admin
  adminPassword: admin-password # Change me!
  hostname: ''
  hostnameStrict: false
  httpEnabled: true
  httpsEnabled: false
  production: false
  extraArgs: []

database:
  type: postgres
  host: ''
  port: ''
  name: keycloak
  username: keycloak
  password: keycloak-db-password # Change me!

# Embedded PostgreSQL
postgres:
  enabled: true
  auth:
    database: keycloak
    username: ''
    password: ''

service:
  type: ClusterIP
  httpPort: 8080
  httpsPort: 8443

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: keycloak.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: '0.5'
    memory: 512Mi

persistence:
  enabled: false
  storageClass: ''
  size: 1Gi

metrics:
  enabled: false
