replicas: 3
minimumMasterNodes: 2

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    network.host: 0.0.0.0

    # 跨域配置
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: Authorization,X-Requested-With,Content-Type,Content-Length

esJavaOpts: "-Xmx1g -Xms1g"

service:
  type: ClusterIP
  port: 9200
  nodePort: ""

xpack:
  enabled: false

clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
