HELM_RELEASE_NAME ?= rocketmq
HELM_APPLICATION_NAME ?= rocketmq
HELM_NAMESPACE ?= rocketmq
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= rocketmq
HELM_REPO_URL ?= https://apache.github.io/rocketmq-helm
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/$(HELM_APPLICATION_NAME)

include ../_template/base.mk
