HELM_RELEASE_NAME ?= nexus
HELM_APPLICATION_NAME ?= nexus-repository-manager
HELM_NAMESPACE ?= nexus
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= sonatype
HELM_REPO_URL ?= https://sonatype.github.io/helm3-charts/
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/$(HELM_APPLICATION_NAME)

include ../_template/base.mk
