HELM_RELEASE_NAME ?= hbase
HELM_APPLICATION_NAME ?= hbase
HELM_NAMESPACE ?= hbase
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= kubeblocks
HELM_REPO_URL ?= https://kubeblocks.io/charts
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/hbase-cluster

include ../_template/base.mk
