HELM_RELEASE_NAME ?= clickhouse-operator
HELM_APPLICATION_NAME ?= clickhouse-operator
HELM_NAMESPACE ?= clickhouse-operator
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= altinity
HELM_REPO_URL ?= https://helm.altinity.com
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/altinity-clickhouse-operator

include ../_template/base.mk