HELM_RELEASE_NAME ?= mysql
HELM_APPLICATION_NAME ?= mysql-innodbcluster
HELM_NAMESPACE ?= mysql
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= mysql-operator
HELM_REPO_URL ?= https://mysql.github.io/mysql-operator/
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/mysql-innodbcluster
HELM_LANE ?=

include ../_template/base.mk
