HELM_RELEASE_NAME ?= pulsar
HELM_APPLICATION_NAME ?= pulsar
HELM_NAMESPACE ?= pulsar
HELM_DIR ?= ./helm
HELM_CHART_VERSION ?=
HELM_VALUES_FILE ?= ./values.yaml
HELM_OCI_REGISTRY ?=
HELM_OCI_NAMESPACE ?=
HELM_OCI_USERNAME ?=
HELM_OCI_PASSWORD ?=
HELM_REPO_NAME ?= apache
HELM_REPO_URL ?= https://pulsar.apache.org/charts
HELM_CHART_REPO ?= $(HELM_REPO_NAME)/pulsar
HELM_LANE ?=

include ../_template/base.mk
